services:
  - type: web
    name: visa-tracking-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash render_start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
