services:
  - type: web
    name: visa-tracking-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install gunicorn
    startCommand: bash render_start.sh
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
